version: '3'

services:

  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}

  gogs:
    image: gogs/gogs:latest
    volumes:
      - gogs-data:/data
    ports:
      - "${PORT_GOGS_SSH}:22"
      - "${PORT_GOGS_GUI}:3000"
    depends_on:
      - mariadb
    networks:
      - devops

networks:
  devops:
    driver: bridge

volumes:
  gogs-data:
  mariadb-data:
