version: '3'

services:

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${PORT_POSTGRES}:5432"
    networks:
      - devops


  bitbucket:
    image: atlassian/bitbucket-server:5.1
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
    ports:
      - "${PORT_BITBUCKET_GUI}:7990"
      - "${PORT_BITBUCKET_SSH}:7999"
    depends_on:
      - postgres
    networks:
      - devops

networks:
  devops:
    driver: bridge

volumes:
  bitbucket-data:
  postgres-data:

