version: '3'

services:

  googs:
    image: gogs/gogs:latest
    volumes:
      - gogs-data:/data
    ports:
      - "${PORT_GOOGS_SSH}:22"
      - "${PORT_GOOGS_GUI}:3000"
    networks:
      - devops

networks:
  devops:
    driver: bridge

volumes:
  gogs-data:

