version: '3'

services:

  gogs:
    image: gogs/gogs:latest
    volumes:
      - gogs-data:/data
    ports:
      - "${PORT_GOGS_SSH}:22"
      - "${PORT_GOGS_GUI}:3000"
    networks:
      - devops

networks:
  devops:
    driver: bridge

volumes:
  gogs-data:

