version: '3'

services:

  bitbucket:
    image: atlassian/bitbucket-server:5.1
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
    ports:
      - 7990:7990
    networks:
      - devops

networks:
  devops:
    driver: bridge

volumes:
  bitbucket-data:

