version: '3'

services:

  gogs:
    image: gogs/gogs:latest
    volumes:
      - gogs-data:/data
    ports:
      - "${PORT_GOGS_SSH}:22"
      - "${PORT_GOGS_GUI}:3000"
    networks:
      - devops

  drone-server:
    image: drone/drone:latest
    ports:
      - ${PORT_DRONE}:8000
    volumes:
      - drone-data:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=${DRONE_GOGS_URL}:${PORT_DRONE}
      - DRONE_GOGS_SKIP_VERIFY=${DRONE_GOGS_SKIP_VERIFY}
      - DRONE_SECRET=${DRONE_SECRET}
    depends_on:
      - gogs
    networks:
      - devops

  drone-agent:
    image: drone/drone:latest
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
    depends_on:
      - drone-server
    networks:
      - devops

networks:
  devops:
    driver: bridge

volumes:
  gogs-data:
  drone-data:

